version: '3.7'

services:
  node:
    image: node:18
    container_name: node
    user: node
    tty: true
    stdin_open: true
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "80:80"
